name: Approved Pull Request
on:
  pull_request_review:
    branches: 
      - main
      - dev
    types: [submitted]
jobs:
  print_env:
    runs-on: [self-hosted]
    steps:
      - name: 'Github Env'
        id: inputs
        env:
          ENV_BRANCH: ${{github.ref}}
          ENV_BRANCH_NAME: ${{github.ref_name}}
          ENV_VALUE: ${{ toJSON(github) }}
        run: |
          echo 'branch name: ${{env.ENV_BRANCH_NAME}}'
          echo 'branch: ${{env.ENV_BRANCH}}'
          echo '${{env.ENV_VALUE}}'
  