name: Build application to deploy
on: [workflow_call]
jobs:
  checkout:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-verison: "14"
      - run: npm ci && npm run test && npm run build
        env:
          CI: true
      - uses: actions/upload-artifact@v3
        with:
          name: application-artiface
          path: |
            build
            .firebaserc
            firebase.json