on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/actions/payload # Uses an action in the root directory
        id: hello
        with:
          trigger: 'push'
      # Use the output from the `hello` step
      - name: Get the output trigger
        run: echo "The trigger was ${{ steps.hello.outputs.trigger }}"