name: Manual test push tag
on: 
  workflow_dispatch:
    inputs:
      debug_env:
        required: false
        type: boolean
        description: 'Print env'
jobs:
  print_env:
    if: github.event.inputs.debug_env == 'true'
    runs-on: [self-hosted]
    steps:
      - name: 'Github Env'
        env:
          ENV_BRANCH: ${{github.ref}}
          ENV_BRANCH_NAME: ${{github.ref_name}}
          ENV_VALUE: ${{ toJSON(github) }}
        run: |
          echo 'branch name: ${{env.ENV_BRANCH_NAME}}'
          echo 'branch: ${{env.ENV_BRANCH}}'
          echo '${{env.ENV_VALUE}}'