name: Manual test hotfix
on:
  workflow_dispatch:
    inputs:
      debug_env:
        required: false
        type: boolean
        description: 'Debug env'
jobs:
  echo_inputs:
    if: github.event.inputs.debug_env == 'true'
    runs-on: [self-hosted]
    steps:
      - name: 'Github Env'
        env:
          ENV_BRANCH: ${{github.ref}}
          ENV_BRANCH_NAME: ${{github.ref_name}}
          ENV_VALUE: ${{ toJSON(github) }}
        run: |
          echo 'branch name: ${{env.ENV_BRANCH_NAME}}'
          echo 'branch: ${{env.ENV_BRANCH}}'
          echo '${{env.ENV_VALUE}}'
  list_commits:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'List commits'
        uses: ./.github/actions/hotfix
        with:
          token: ${{secrets.GITHUB_TOKEN}}