name: Manaul test approved pull request
on:
  workflow_dispatch:
    inputs:
      debug_env:
        required: false
        type: boolean
        description: 'Debug env'
jobs:
  print_env:
    if: github.event.inputs.debug_env == 'true'
    runs-on: [self-hosted]
    steps:
      - name: 'Github Env'
        env:
          ENV_BRANCH_NAME: ${{github.ref_name}}
          ENV_BRANCH: ${{github.ref}}
          ENV_VALUE: ${{ toJSON(github) }}
        run: |
          echo 'branch name: ${{env.ENV_BRANCH_NAME}}'
          echo 'branch: ${{env.ENV_BRANCH}}'
          echo '${{env.ENV_VALUE}}'
  # checkout_github:
  #   runs-on: [self-hosted]
  #   steps:
  #     - uses: actions/checkout@v2
  # build_test:
  #   needs: checkout_github
  #   runs-on: [self-hosted]
  #   steps:
  #     - run: 'echo Build test'
  # test:
  #   needs: build_test
  #   runs-on: [self-hosted]
  #   steps:
  #     - run: 'echo build test'
  # build_deploy:
  #   needs: test
  #   runs-on: [self-hosted]
  #   steps:
  #     - run: 'echo Build deploy'
  # deploy_staging:
  #   needs: test
  #   if: github.ref_name == 'dev'
  #   runs-on: [self-hosted]
  #   steps:
  #     - run: 'echo Deploy staging'
  # deploy_production:
  #   needs: test
  #   if: github.ref_name == 'main'
  #   runs-on: [self-hosted]
  #   steps:
  #     - run: 'echo Deploy production'

  