name: Manual test merged hotfix
on: [workflow_dispatch]
jobs:
  rebase_re_open_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'List commits'
        uses: ./.github/actions/merge_hotfix
        with:
          token: ${{secrets.GITHUB_TOKEN}}