name: 'Sematic Versioning'
on:
  workflow_dispatch:
jobs:
  generate_semantic_versioning:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'List commits'
        uses: ./.github/actions/semver
        with:
          token: ${{secrets.GITHUB_TOKEN}}